name: Robô Atualizador da ANA

on:
  schedule:
    # Roda duas vezes ao dia: às 05:00 e 17:00 (Horário de Brasília -> 08:00 e 20:00 UTC)
    - cron: '0 8,20 * * *'
  workflow_dispatch: # Permite rodar o script manualmente clicando num botão

jobs:
  sincronizar_dados:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm install firebase xml2js

    - name: Executar Robô de Atualização (Firebase)
      run: node robo_ana.mjs

    - name: Baixar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependências Python
      run: pip install requests
        
    - name: Executar Robô Sipam -> estacoes.json
      run: python robo_censipam.py
      
    - name: Commit e Push das alterações
      run: |
        git config --global user.name 'Robô ANA'
        git config --global user.email 'caiqueamarall@users.noreply.github.com'
        git add public/estacoes.json
        git commit -m "🤖 Atualização Automática de Dados (Sipam + ANA)" || echo "Sem mudanças"
        git push
